### PR TITLE
support producing XML output from unit tests

### PR DESCRIPTION
**Pull request by boegel**
use xmlrunner when available, so we can get XML output that can be used by Jenkins

### CODE REVIEW

**Comment by boegel** [comment]
Fixed all the issues that we were having, this should be ready to review for merging.

**Comment by boegel** [comment]
Unit test now fully passes on gengar cluster (Python 2.4) when run as `python easybuild/test/suite.py`, and on Jenkins CI server (Python 2.6), see http://jenkins1.ugent.be/job/EasyBuild_unit_test/11/testReport/ .

**Comment by JensTimmerman** [comment]
Ok

Howevever I'm not sure we weant to include the TEMPLATE.eb in the test directory, 
we're not really testing the real TEMPLATE.eb then...

So maybe this TEMPLATE should be moved into framework, and not be in easyconfigs?

**Comment by boegel** [comment]
Fixed all issues.

Unit test now also runs correctly outside of directory where EasyBuild framework is installed.

`TEMPLATE.eb` file is no longer included in `test` dir.

**Pull request merged**
